#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    controller:  App\Controller\PictureController::index
    defaults:
        path: /en
        permanent: true

oauth_check:
    path:          /oauth/check/{service}
    controller:    App\Controller\PictureController::index
